version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - keycloak
      - app

  # Keycloak (Auth)
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: auth.alabuga-start.ru
      KC_PROXY: edge  # Для работы за reverse proxy
    command: start-dev --import-realm
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    networks:
      app-network:
        aliases:
          - auth.alabuga-start.ru  # Алиас для Keycloak
    depends_on:
      - keycloak_db

  # PostgreSQL для Keycloak
  keycloak_db:
    image: postgres:latest
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # PostgreSQL для Keycloak
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      POSTGRES_DB: alabuga
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Laravel (Portal)
  app:
    build: ./app
    container_name: portal
    # volumes:
    #  - ./app:/var/www/html
    env_file:
      - app/.env
    networks:
      app-network:
        aliases:
          - portal.alabuga-start.ru  # Алиас для App
    depends_on:
      - app_db

volumes:
  app_db_data:
  keycloak_db_data:

networks:
  app-network:
    driver: bridge
